name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  build_skim:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          COMPILER=$(root-config -cxx)
          $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx
